import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "../globals.css";
import { Navbar } from "@/app/(root)/components/navbar";

const roboto = Manrope({
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Car Dealer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} h-full bg-gray-100  w-full antialiased`}
      >
        <Navbar />

        <main className="w-full h-full">{children}</main>
      </body>
    </html>
  );
}

const paddings = "max-w-screen-2xl px-12 sm:px-16 md:px-24 lg:px-44 py-12  ";
