import type { Metadata } from "next";
import {
    Geist,
    Geist_Mono,
    Lato, Manrope,
    Noto_Sans,
    Nunito,
    Nunito_Sans,
    Open_Sans,
    Poppins,
    Roboto,
    Sansita
} from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


const roboto = Manrope({
    weight: '400',
    subsets: ['latin'],
})
export const metadata: Metadata = {
  title: "Car Dealer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <header className="h-16 py-2 px-20 flex items-center  text-white bg-black">

        </header>
        <main className=" px-6">
            {children}
        </main>
      </body>
    </html>
  );
}
