import type { Metadata } from "next";
import {
    Geist,
    Geist_Mono,
    Lato, Manrope,
    Noto_Sans,
    Nunito,
    Nunito_Sans,
    Open_Sans,
    Poppins,
    Roboto,
    Sansita
} from "next/font/google";
import "./globals.css";
import {Home} from "lucide-react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


const roboto = Manrope({
    weight: '400',
    subsets: ['latin'],
})
export const metadata: Metadata = {
  title: "Car Dealer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} h-full w-full antialiased`}
      >
        <header className="bg-gray-100 py-4">
            <Home className="right-0  left-0 m-auto"/>
        </header>


        <main className="w-full px-12 py-6 h-full">
            {children}
        </main>
      </body>
    </html>
  );
}
